const sampleData = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: "123456",
      role: "admin",
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: "123456",
      role: "user",
    },
  ],
  products: [
    {
      name: "Andy No.5 for men.",
      slug: "andy-no5-for-men",
      category: "Men perfume best seller",
      description: "A classic scent that exudes confidence and sophistication",
      images: [
        "/images/sample-products/0002.jpg",
        "/images/sample-products/0003.jpg",
      ],
      price: 59.99,
      brand: "AndyOud",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "/images/banner_0014.jpg",
    },
    {
      name: "Thailand Mush smoothly aroma",
      slug: "thailand-mush-smoothly-aroma",
      category: "Men's Men Perfume",
      description: "Best quality perfume for daily use for adults",
      images: [
        "/images/sample-products/0001.jpg",
        "/images/sample-products/0008.jpg",
      ],
      price: 85.9,
      brand: "AndyOud",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "/images/banner-2.jpg",
    },
    {
      name: "Andy No.7 for men.",
      slug: "andy-no7-for-men",
      category: "Men perfume best seller",
      description: "A modern fragrance that combines freshness with depth",
      images: [
        "/images/sample-products/0007.jpg",
        "/images/sample-products/0005.jpg",
      ],
      price: 99.95,
      brand: "AndyOud",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Angkor Chill",
      slug: "angkor-chill",
      category: "Men's Men Perfume of all time",
      description: "Smooth and relaxing fragrance inspired by Angkor Wat",
      images: [
        "/images/sample-products/0012.jpg",
        "/images/sample-products/0013.jpg",
      ],
      price: 39.95,
      brand: "AndyOud",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Cambodia Musk",
      slug: "cambodia-musk",
      category: "Men's Men Perfume of all time",
      description: "A bold and captivating scent with rich musk undertones",
      images: [
        "/images/sample-products/0009.jpg",
        "/images/sample-products/0010.jpg",
      ],
      price: 79.99,
      brand: "AndyOud",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Cambodia Floral",
      slug: "cambodia-floral",
      category: "Men's Men Perfume of all time",
      description:
        "A fresh and floral fragrance that captures the essence of Cambodian gardens",
      images: [
        "/images/sample-products/0010.jpg",
        "/images/sample-products/0011.jpg",
      ],
      price: 99.99,
      brand: "AndyOud",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: "/images/banner_0015.jpg",
    },
  ],
};

export default sampleData;
